"""added ratings

Revision ID: ca1da97e09e8
Revises: 
Create Date: 2023-08-03 09:31:46.230065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca1da97e09e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_ratings', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('num_ratings', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.drop_column('num_ratings')
        batch_op.drop_column('user_ratings')

    op.create_table('rating',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('show_id', sa.INTEGER(), nullable=False),
    sa.Column('rating_value', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
